---

title: "Music diversity and circulation: Novel data collection methods and indicators"
subtitle: "DOI: 10.5281/zenodo.6465135"
author:
- Daniel Antal, CFA, Reprex & University of Amsterdam
- Scanga, Cateriana, PhD, Scuola Superiore Sant'Anna
- Molina, Andrés GJ, PhD, Reprex
date: "`r Sys.Date()`"
output:
  pdf_document: default
  md_document: default
  word_document: default
  html_document: default
bibliography:
- datascience.bib
- mme.bib
- legalccsi.bib
- antal.bib
- competition.bib
- caselaw.bib
- dcms.bib
- digitalmusicobservatory.bib
- packages.bib
- musicindustry.bib
- musicology.bib
- statisticalmethodology.bib
- datainteroperability.bib
- eulaw.bib
- openscience.bib
- opa.bib
- opendata.bib
- rpackages.bib
- valuation.bib
- valuegap.bib

---

```{r setupdmoeconomypillar, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, out.width = '95%', fig.align = 'center')
library(knitr)
library(here)
here::here()
```

## Abstract

In the last decade, the evidence-based policy movement gained significant traction in Europe as well as globally. Its focus has been to increase the rigour of the evidence generated, to improve the credibility and understandability of evidence created for policy purposes.  As evidence-based policies often rely on scientific evidence, the evidence-based policy movement went hand in hand with the efforts to increase the transparency and reproducibility of scientific research (See: [@manifesto_for_reproducible_science_2017] and in an EU context [@JRC99722; @reproducibility_scientific_results_eu_2020; @progress_open_science_2020].)  

Our [Report on Music Diversity and Circulation in Europe](https://zenodo.org/record/6465114#.YlsMz9pBzIU), and its supporting document, [Music diversity and circulation: Novel data collection methods and indicators](https://doi.org/10.5281/zenodo.6465135) will follow the Open Policy Analysis Guidelines and the best practices of the European Union's Knowledge For Policy and the [European Open Science Cloud](https://eosc-portal.eu/) portal.  

The aim of this document is to *share an open report that includes clear accounts of all methodological procedures, data, and assumptions.* Best practice: All project components are organized in a selfcontained folder using a Standard File Structure (SFS), and a readme file is included. We place all files with SFS on the European open science repository Zenodo on [zenodo.org/communities/music_observatory/](https://zenodo.org/communities/music_observatory/).

Subjects: [Reproducible research](https://id.loc.gov/authorities/subjects/sh2013002574.html); [Cultural diversity policies](https://id.loc.gov/authorities/subjects/sh93001610.html); [Music industry](https://id.loc.gov/authorities/subjects/sh85088944.html)
[Recommender systems (Information filtering)](https://id.loc.gov/authorities/subjects/sh2007003098.html)

You can find the repository of this document on [GitHub](https://openmuse.dataobservatory.eu/resources/report-music-diversity-circulation/)

Antal, Daniel, Scanga, Cateriana, & Molina, Andrés GJ. (2022). Music diversity and circulation: Novel data collection methods and indicators (0.1). Zenodo. https://doi.org/10.5281/zenodo.6465135